### ISSUE TITLE
weird issue with non-integers staying in memory after being rejected

### ISSUE THREAD

**Issue by ErrorRaffyline0** [ErrorRaffyline0/LnW-Java-Players-Guide#1]
in [#src/pkg/eindopdracht/eindopdracht02.java](https://github.com/ErrorRaffyline0/LnW-Java-Players-Guide/blob/main/src/pkg/eindopdracht/eindopdracht02.java), if you input a (number of) non-integer(s) before inputting a valid integer, the process still crashes on the last non-integer.
error log: 
```
Input an integer: 769827368972689472368942689364289376489273649827364892673423742638946723
Not an integer!
Input an integer: 32948267349827649872639847269873642897634982674897269836498768976249836749823
Not an integer!
Input an integer: 28364982736489267348972634897263894726893746287364987263498723649872639478623
Not an integer!
Input an integer: 2376492873648927364827634982768976986798769999932897468373333
Not an integer!
Input an integer: 3373
Input an integer: Exception in thread "main" java.util.InputMismatchException: For input string: "2376492873648927364827634982768976986798769999932897468373333"
	at java.util.Scanner.nextInt(Scanner.java:2123)
	at java.util.Scanner.nextInt(Scanner.java:2076)
	at pkg.eindopdracht.eindopdracht02.CheckInput(eindopdracht02.java:43)
	at pkg.eindopdracht.eindopdracht02.CheckInput(eindopdracht02.java:40)
	at pkg.eindopdracht.eindopdracht02.CheckInput(eindopdracht02.java:40)
	at pkg.eindopdracht.eindopdracht02.CheckInput(eindopdracht02.java:40)
	at pkg.eindopdracht.eindopdracht02.main(eindopdracht02.java:6)

Process finished with exit code 1

```

**Comment by ErrorRaffyline0** [comment]
fixed
